language: node_js

node_js:
  - stable

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - npm test
        - bash <(curl -s https://codecov.io/bash)
    - script:
        - echo "other"
    - stage: deploy  
      name: "Publish to NPM"
      if: branch = master
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: true